apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgAOLY1G4VjU2GI5VcZuXWvv+EHHDHtV2OqyyyGaGtJ1V9LBHbDRfF10QHsQA7q6HyzLso8x5ErAHaUvDBTlELpb2HJiB6s67H2FfztkLI/f5GDHC1BOlfe+9279fs4g/LXw4cGrZfl+xFLD8KFESkPR2+2/gTBmW6yFJtQjsR2XBy9A3LFBonYj6PZZnomtSGTz7Yf3aqysjOuT8lI0I+7Lzvp2uLL3ByeCMqSVN2OhoAhTOOXHEuwOKjbMn+IBieXcXnTj0+lOFLY9jSii/Gg2uSHFIaNu6bVFDI+4QHcxNuZKFBNt9vUwNouBeWGVPo7HdTiZOU2hGbTTh8hbgp9cVAcUarFFkWIBmSdeACSshKO88TkdCtwjglFjWGuxtfGi4q1EXVmKEzv0Q6O13dzN3zni5t/SuQq/i8z99/StUv5+fLhSk1BDdAWcb/5B0W+bszKTQT92ceH+990r2lqrw8lUDf0+Uv+wYJwnjUt9pop41T+xnnoAAOPFzKpII1D1YOGo+33MMxlGQj2qbXggTsEAnkH/avrvURcfvags0Isz82/agh9heTG3pfeAD0F9YlpXgaA4L9IpiiATx4bs6wb//7JVEyl1rGIGogNKDOw+T5M0tV/7GNaIWWN11LLTOATeQyKnOaDWHHQY7RQAEmVCZLlPnceSxj9/lO1rvgGexAlxahR+FR3Vs+1QvE2WhhAtbqbhZxmtJqfW1yS2vjg3TTAao5y/MBnOMeo+lrWP74XG5DFc
    username: AgCnxFQgeLc/rR9bOgzIM7AD8xQovmyPJPtEmum20M+RH672UXsJBc0xHh4wgAAXthWtikC7zZvn54pwcQmSj3qpW8U9Ja9j2lGkNtB7Mgk4/4r3ShIvyDqwuSRjQzk1WaSnEc6kteDKtq/M9jqr/iFBbKZuocCQVq7lVyBL0nW83FFhTZbG8YLqu4EK6RxRmJSR1IOQuGxjzB09n/DwO6YTyxYEn0VmvW895mj+seW6qgvuV3+Yw+ctzanN84nBLdNGO8ewTjlMPHJda9oxWEWuP2hm7zlCDvJWcDr/7Q8qwrJGvFTchi8ug+n7gI2cprik2DZeNLpiEkvYjlZYPB5g+5ZO5GvN5uFECjLdhqIxcomPokBUk7Fb20YdY6BRsBtvUP/8AC/+MGEWEup+PMhI8/G9MToFKPFs6ZgZypIKNo8u/aMQNR4ykSwyHaMy7jKR7kA7oP7dHKwZtzlWGAuK+QaJymap+TN0mHmtgf/pyIfSUcbBmpiITLXLJIO2ro4YSEetMJ1kmSYF7DagoXS4l3Hv3Js6PwawUGZqVKvWWqLXY3/Zm2L8eJ9QJLXo44jXmtBYfuup7HvTmXGwrKDraj3kn+XCR2tZzvPM8Ey9yx8GvpQHKTd5UzdjJyBw7P47Bm2Gi3JHaNkZnOaDKz8qfA4aLygAyyREvLH7kzqEAuw2DfRTeR18DVk2L66mHspC1IoomQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

